title="config"

[manager]
period=1800

[wallhaven]
[[wallhaven.config]]
page=1
categories="anime"
tag="anime"
[[wallhaven.config]]
page=2
categories="anime"
tag="anime"
[[wallhaven.config]]
page=3
categories="anime"
tag="anime"
