Document: wallpaper-toolbox
Title: Debian wallpaper-toolbox Manual
Author: <insert document author here>
Abstract: This manual describes what wallpaper-toolbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wallpaper-toolbox/wallpaper-toolbox.sgml.gz

Format: postscript
Files: /usr/share/doc/wallpaper-toolbox/wallpaper-toolbox.ps.gz

Format: text
Files: /usr/share/doc/wallpaper-toolbox/wallpaper-toolbox.text.gz

Format: HTML
Index: /usr/share/doc/wallpaper-toolbox/html/index.html
Files: /usr/share/doc/wallpaper-toolbox/html/*.html
